docs_dir: docs/content
nav:
- Home: index.md
- Examples: examples.md
- Brel Filings:
  - Filings: brel-filings/filings.md
- Facts:
  - Facts: facts/facts.md
  - Contexts: facts/contexts.md
  - Aspects: facts/aspects.md
  - Characteristics: facts/characteristics.md
  - Concept Characteristic: facts/concept-characteristic.md
  - Entity Characteristic: facts/entity-characteristic.md
  - Period Characteristic: facts/period-characteristic.md
  - Unit Characteristic: facts/unit-characteristic.md
  - Explicit Dimension Characteristic: facts/explicit-dimension-characteristic.md
  - Typed Dimension Characteristic: facts/typed-dimension-characteristic.md
- Components:
  - Components: components/components.md
  - Networks: components/networks.md
  - Network Nodes: components/network-nodes.md
  - Calculation Networks and Nodes: components/calculation-networks-and-nodes.md
- Report Elements:
  - Report Elements: report-elements/report-elements.md
  - Concept: report-elements/concept.md
  - Abstract: report-elements/abstract.md
  - Line Items: report-elements/line-items.md
  - Hypercube: report-elements/hypercube.md
  - Dimension: report-elements/dimension.md
  - Member: report-elements/member.md
- QNames:
  - QNames and Namespace maps: qnames/qnames-and-namespace-maps.md
  - Namespace normalization: qnames/namespace-normalization.md
repo_url: https://github.com/PapediPoo/Brel
site_name: Brel git repo
theme: readthedocs
