from enum import Enum


class Area(Enum):
    SCHEMA_DEFINITION = "SCH"
    GENERAL_INSTANCE = "ING"
    IXBRL_INSTANCE = "INI"
    XML_INSTANCE = "INX"
    JSON_INSTANCE = "INJ"
    CSV_INSTANCE = "INC"
    CALCULATION_NETWORK = "CAL"
    PRESENTATION_NETWORK = "PRE"
    DEFINITION_NETWORK = "DEF"
    FOOTNOTE_NETWORK = "FOO"
    LABEL_NETWORK = "LAB"
    REFERENCE_NETWORK = "REF"
    VALIDATION = "VAL"
    MISC = "MSC"
