from enum import Enum

class ErrorCode(Enum):
    MISSING_CONTEXT_PERIOD = "MISSING_CONTEXT_PERIOD", 
    MISSING_CONTEXT_ENTITY = "MISSING_CONTEXT_ENTITY",
    INVALID_DIMENSION_TYPE = "INVALID_DIMENSION_TYPE",
    
    XML_DUPLICATE_UNIT_ID = "DUPLICATE_UNIT_ID",
    XML_UNIT_ELEMENT_WITHOUT_ONE_CHILD = "MULTIPLE_UNIT_CHILDREN",
    XML_DIVIDE_ELEMENT_WITHOUT_TWO_CHILDREN = "DIVIDE_WITH_MORE_OR_LESS_THAN_TWO_CHILDREN",
    XML_INVALID_DIVIDE_ELEMENT_CHILDREN = "INVALID_DIVIDE_ELEMENT_CHILDREN",
    XML_DUPLICATE_DIVIDE_ELEMENT_CHILDREN = "DUPLICATE_DIVIDE_ELEMENT_CHILDREN",
    XML_INVALID_UNIT_ELEMENT_CHILDREN = "INVALID_UNIT_ELEMENT_CHILDREN",
    XML_MISSING_UNIT_MEASURE = "MISSING_UNIT_MEASURE",

    IXBRL_DUPLICATE_ELEMENT_ID = "IXBRL_DUPLICATE_ELEMENT_ID",
    IXBRL_ELEMENT_NOT_SUPPORTED = "IXBRL_ELEMENT_NOT_SUPPORTED",

    IXBRL_REFERENCES_ELEMENT_WITHOUT_CHILDREN = "IXBRL_REFERENCES_ELEMENT_WITHOUT_CHILDREN",
    IXBRL_INVALID_REFERENCES_CHILD = "IXBRL_INCOMPATIBLE_REFERENCES_CHILDREN",
    IXBRL_HEADER_ELEMENT_IN_HEAD = "IXBRL_HEADER_ELEMENT_IN_HEAD",
    IXBRL_INVALID_HEADER_CHILD = "IXBRL_INVALID_HEADER_CHILD",
    IXBRL_MORE_THAN_ONE_HIDDEN_HEADER_CHILD = "IXBRL_MORE_THAN_ONE_HIDDEN_HEADER_ELEMENT",
    IXBRL_MORE_THAN_ONE_RESOURCES_HEADER_CHILD = "IXBRL_MORE_THAN_ONE_RESOURCES_HEADER_CHILD",
    IXBRL_NO_HEADER_ELEMENTS = "IXBRL_NO_HEADER_ELEMENTS",
    IXBRL_NO_RESOURCES_ELEMENTS = "IXBRL_NO_RESOURCES_ELEMENTS",
    IXBRL_INVALID_RESOURCES_CHILD = "IXBRL_INVALID_RESOURCES_CHILD",
    IXBRL_CONTEXT_WITHOUT_ID = "IXBRL_CONTEXT_WITHOUT_ID",
    IXBRL_UNIT_WITHOUT_ID = "IXBRL_UNIT_WITHOUT_ID",

    
    IXBRL_INVALID_HIDDEN_ELEMENT = "IXBRL_INVALID_HIDDEN_ELEMENT",
    
    IXBRL_FACT_WITHOUT_CONTEXT = "IXBRL_FACT_WITHOUT_CONTEXT",
    IXBRL_INVALID_FACT_CONTEXT_ID = "IXBRL_INVALID_FACT_CONTEXT_ID",
    IXBRL_FACT_WITHOUT_CONCEPT_NAME = "IXBRL_FACT_WITHOUT_CONCEPT_NAME",
    
    
