from enum import Enum


class ErrorCode(Enum):
    MISSING_CONTEXT_PERIOD = ("MISSING_CONTEXT_PERIOD",)
    MISSING_CONTEXT_ENTITY = ("MISSING_CONTEXT_ENTITY",)
    INVALID_CONTEXT_PERIOD_DATE = ("INVALID_CONTEXT_PERIOD_DATE",)
    DURATION_PERIOD_MISSING_START_DATE = ("DURATION_PERIOD_MISSING_START_DATE",)
    DURATION_PERIOD_MISSING_END_DATE = ("DURATION_PERIOD_MISSING_END_DATE",)
    DURATION_PERIOD_START_AFTER_END = ("DURATION_PERIOD_START_AFTER_END",)
    INVALID_DIMENSION_ATTRIBUTE_VALUE = ("INVALID_DIMENSION_ATTRIBUTE_VALUE",)
    INVALID_DIMENSION_MEMBER = ("INVALID_DIMENSION_MEMBER",)
    INVALID_DIMENSION_TYPE = ("INVALID_DIMENSION_TYPE",)
    INVALID_PRECISION_ATTRIBUTE_VALUE = ("INVALID_PRECISION_ATTRIBUTE_VALUE",)
    INVALID_DECIMALS_ATTRIBUTE_VALUE = ("INVALID_DECIMALS_ATTRIBUTE_VALUE",)
    MISSING_FACT_VALUE = ("MISSING_FACT_VALUE",)
    FACT_UNIT_MISMATCH = ("FACT_UNIT_MISMATCH",)
    FACT_CONCEPT_MISMATCH = ("FACT_CONCEPT_MISMATCH",)
    QNAME_NAMESPACE_NOT_IN_ELEMENT_SCOPE = ("QNAME_NAMESPACE_NOT_IN_ELEMENT_SCOPE",)
    QNAME_MISSING_NAMESPACE = ("QNAME_MISSING_NAMESPACE",)
    XML_DUPLICATE_UNIT_ID = ("DUPLICATE_UNIT_ID",)
    XML_UNIT_ELEMENT_WITHOUT_ONE_CHILD = ("MULTIPLE_UNIT_CHILDREN",)
    XML_DIVIDE_ELEMENT_WITHOUT_TWO_CHILDREN = (
        "DIVIDE_WITH_MORE_OR_LESS_THAN_TWO_CHILDREN",
    )
    XML_INVALID_DIVIDE_ELEMENT_CHILDREN = ("INVALID_DIVIDE_ELEMENT_CHILDREN",)
    XML_DUPLICATE_DIVIDE_ELEMENT_CHILDREN = ("DUPLICATE_DIVIDE_ELEMENT_CHILDREN",)
    XML_INVALID_UNIT_ELEMENT_CHILDREN = ("INVALID_UNIT_ELEMENT_CHILDREN",)
    XML_MISSING_UNIT_MEASURE = ("MISSING_UNIT_MEASURE",)

    IXBRL_DUPLICATE_ELEMENT_ID = ("IXBRL_DUPLICATE_ELEMENT_ID",)
    IXBRL_ELEMENT_NOT_SUPPORTED = ("IXBRL_ELEMENT_NOT_SUPPORTED",)

    IXBRL_REFERENCES_ELEMENT_WITHOUT_CHILDREN = (
        "IXBRL_REFERENCES_ELEMENT_WITHOUT_CHILDREN",
    )
    IXBRL_INVALID_REFERENCES_CHILD = ("IXBRL_INCOMPATIBLE_REFERENCES_CHILDREN",)
    IXBRL_HEADER_ELEMENT_IN_HEAD = ("IXBRL_HEADER_ELEMENT_IN_HEAD",)
    IXBRL_INVALID_HEADER_CHILD = ("IXBRL_INVALID_HEADER_CHILD",)
    IXBRL_MORE_THAN_ONE_HIDDEN_HEADER_CHILD = (
        "IXBRL_MORE_THAN_ONE_HIDDEN_HEADER_ELEMENT",
    )
    IXBRL_MORE_THAN_ONE_RESOURCES_HEADER_CHILD = (
        "IXBRL_MORE_THAN_ONE_RESOURCES_HEADER_CHILD",
    )
    IXBRL_NO_HEADER_ELEMENTS = ("IXBRL_NO_HEADER_ELEMENTS",)
    IXBRL_NO_RESOURCES_ELEMENTS = ("IXBRL_NO_RESOURCES_ELEMENTS",)
    IXBRL_INVALID_RESOURCES_CHILD = ("IXBRL_INVALID_RESOURCES_CHILD",)
    IXBRL_CONTEXT_WITHOUT_ID = ("IXBRL_CONTEXT_WITHOUT_ID",)
    IXBRL_UNIT_WITHOUT_ID = ("IXBRL_UNIT_WITHOUT_ID",)

    IXBRL_INVALID_HIDDEN_ELEMENT = ("IXBRL_INVALID_HIDDEN_ELEMENT",)

    IXBRL_FACT_WITHOUT_CONTEXT = ("IXBRL_FACT_WITHOUT_CONTEXT",)
    IXBRL_INVALID_FACT_CONTEXT_ID = ("IXBRL_INVALID_FACT_CONTEXT_ID",)
    IXBRL_INVALID_FACT_UNIT_ID = ("IXBRL_INVALID_FACT_UNIT_ID",)
    IXBRL_FACT_WITHOUT_CONCEPT_NAME = ("IXBRL_FACT_WITHOUT_CONCEPT_NAME",)
    IXBRL_FACT_INVALID_CONCEPT = ("IXBRL_INVALID_CONCEPT",)
    IXBRL_NON_FRACTION_WITHOUT_UNIT = ("IXBRL_NON_FRACTION_WITHOUT_UNIT",)
    IXBRL_MUTUALLY_EXCLUSIVE_ATTRIBUTES_IN_NON_FRACTION = (
        "IXBRL_MUTUALLY_EXCLUSIVE_ATTRIBUTES_IN_NON_FRACTION",
    )

    IXBRL_BOTH_TEXT_AND_CHILDREN_IN_NON_FRACTION = (
        "IXBRL_BOTH_TEXT_AND_CHILDREN_IN_NON_FRACTION",
    )
    IXBRL_TEXT_OR_CHILDREN_WITH_NIL = ("IXBRL_TEXT_OR_CHILDREN_WITH_NIL",)
    IXBRL_NO_TEXT_OR_CHILDREN_WITH_ABSENT_NIL_ATTRIBUTE = {
        "IXBRL_NO_TEXT_OR_CHILIDREN_WITH_ABSENT_NIL_ATTRIBUTE",
    }
    IXBRL_INVALID_SIGN_ATTRIBUTE_VALUE = ("IXBRL_INVALID_SIGN_ATTRIBUTE",)
    IXBRL_MULTIPLE_NON_FRACTION_CHILDREN = ("IXBRL_MULTIPLE_NON_FRACTION_CHILDREN",)
    IXBRL_INVALID_NON_FRACTION_CHILD = ("IXBRL_INVALID_NON_FRACTION_CHILDREN",)
    IXBRL_NON_NUMERICAL_NON_FRACTION_FACT_VALUE = (
        "IXBRL_NON_NUMERICAL_NON_FRACTION_FACT_VALUE",
    )
    IXBRL_NEGATIVE_NON_FRACTION_FACT_VALUE = ("IXBRL_NEGATIVE_NON_FRACTION_FACT_VALUE",)
    IXBRL_NIL_ATTRIBUTE_IN_NON_FRACTION_CHILD = (
        "IXBRL_NIL_ATTRIBUTE_IN_NON_FRACTION_CHILD",
    )
    IXBRL_DIFFERING_FORMAT_SCALE_OR_UNIT_FOR_NON_FRACTION_CHILD = (
        "IXBRL_DIFFERING_FORMAT_SCALE_OR_UNIT_FOR_NON_FRACTION_CHILD",
    )

    IXBRL_INVALID_NON_NUMERIC_FACT_ESCAPE_ATTRIBUTE_VALUE = (
        "IXBRL_INVALID_NON_NUMERIC_FACT_ESCAPE_ATTRIBUTE_VALUE",
    )
    IXBRL_CONTINUATION_WITHOUT_ID = ("IXBRL_CONTINUATION_WITHOUT_ID",)

    IXBRL_REUSED_CONTINUATION = ("IXBRL_REUSED_CONTINUATION",)
    IXBRL_INVALID_CONTINUATION_ID = ("IXBRL_INVALID_CONTINUATION_ID",)
    IXBRL_INVALID_DESCENDANT_IN_CONTINUATION_CHAIN = (
        "IXBRL_INVALID_DESCENDANT_IN_CONTINUATION_CHAIN",
    )
    IXBRL_UNUSED_CONTINUATION_ELEMENTS = ("IXBRL_UNUSED_CONTINUATION_ELEEMENTS",)

    IXBRL_FOOTNOTE_WITHOUT_ID = ("IXBRL_FOOTNOTE_WITHOUT_ID",)
    IXBRL_INVALID_FOOTNOTE_ROLE = ("IXBRL_INVALID_FOOTNOTE_ROLE",)
    IXBRL_FOOTNOTE_WITHOUT_LANGUAGE = ("IXBRL_FOOTNOTE_WITHOUT_LANGUAGE",)

    IXBRL_RELATIONSHIP_WITHOUT_FROMREFS = ("IXBRL_RELATIONSHIP_WITHOUT_FROMREFS",)
    IXBRL_RELATIONSHIP_WITHOUT_TOREFS = ("IXBRL_RELATIONSHIP_WITHOUT_TOREFS",)
    IXBRL_RELATIONSHIP_REPEATED_ID = ("IXBRL_RELATIONSHIP_REPEATED_ID",)
    IXBRL_RELATIONSHIP_INVALID_FACT_ID_IN_FROMREFS = (
        "IXBRL_RELATIONSHIP_INVALID_FACT_ID_IN_FROMREFS",
    )
    IXBRL_RELATIONSHIP_INVALID_FACT_OR_FOOTNOTE_ID_IN_TOREFS = (
        "IXBRL_RELATIONSHIP_INVALID_FACT_OR_FOOTNOTE_ID_IN_TOREFS",
    )
    IXBRL_RELATIONSHIP_MIXED_FACT_AND_FOOTNOTES_IN_TOREFS = (
        "IXBRL_RELATIONSHIP_MIXED_FACT_AND_FOOTNOTES_IN_TOREFS",
    )
    IXBRL_RELATIONSHIP_INVALID_ARCROLE = ("IXBRL_RELATIONSHIP_INVALID_ARCROLE",)
    IXBRL_RELATIONSHIP_INVALID_LINKROLE = ("IXBRL_RELATIONSHIP_INVALID_LINKROLE",)
    IXBRL_RELATIONSHIP_INVALID_ORDER = ("IXBRL_RELATIONSHIP_INVALID_ORDER",)

    # General linkbase
    ROLEREF_INVALID_LINKTYPE = ("LINKBASE_INVALID_ROLEREF_LINKTYPE",)
    ROLEREF_MISSING_HREF_ATTRIBUTE = ("LINKBASE_ROLEREF_MISSING_HREF_ATTRIBUTE",)
    ROLEREF_INVALID_HREF_ATTRIBUTE = ("LINKBASE_ROLEREF_INVALID_HREF_ATTRIBUTE",)
    ROLEREF_MISSING_ROLE_URI_ATTRIBUTE = (
        "LINKBASE_ROLEREF_MISSING_ROLE_URI_ATTRIBUTE",
    )
    ROLEREF_INVALID_ROLE_URI_ATTRIBUTE = (
        "LINKBASE_ROLEREF_INVALID_ROLE_URI_ATTRIBUTE",
    )
    ROLEREF_EMPTY_ROLE_ATTRIBUTE = ("LINKBASE_ROLEREF_EMPTY_ROLE_ATTRIBUTE",)

    # Validation
    MULTIPLE_PRESENTATION_NETWORKS_IN_COMPONENT = (
        "MULTIPLE_PRESENTATION_NETWORKS_IN_COMPONENT",
    )
    MULTIPLE_CALCULATION_NETWORKS_IN_COMPONENT = (
        "MULTIPLE_CALCULATION_NETWORKS_IN_COMPONENT",
    )
    MULTIPLE_DEFINITION_NETWORKS_IN_COMPONENT = (
        "MULTIPLE_DEFINITION_NETWORKS_IN_COMPONENT",
    )

    # Schema
    PRESENTATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT = (
        "PRESENTATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT",
    )
    CALCULATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT = (
        "CALCULATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT",
    )
    DEFINITION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT = (
        "DEFINITION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT",
    )
