from typing import Any, Dict, Optional, Union

from brel.errors.area import Area
from brel.errors.error_code import ErrorCode
from brel.errors.severity import Severity
from brel.qnames.qname import QName

error_namespaces = {"tpe": "http://xbrl.org/2016/taxonomy-package/errors"}

error_registry: Dict[ErrorCode, Dict[str, Union[Severity, Area, str, QName]]] = {
    ErrorCode.MISSING_CONTEXT_PERIOD: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "000",
        "message": "Context is missing a period child element",
        "hint": "Check the definition of the context.",
    },
    ErrorCode.MISSING_CONTEXT_ENTITY: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "001",
        "message": "Context is missing an entity child element",
        "hint": "Check the definition of the context.",
    },
    ErrorCode.INVALID_DIMENSION_TYPE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "002",
        "message": "Dimension type '{dimension_type}' is not valid. It should either be 'explicitMember' or typedMember'.",
        "hint": "Check the segment part of the context.",
    },
    ErrorCode.INVALID_CONTEXT_PERIOD_DATE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "003",
        "message": "Date '{date}' is not a valid date.",
        "hint": "Check the text contents of the <period> element. Dates should be in the ISO 8601 format (YYYY-MM-DD).",
    },
    ErrorCode.DURATION_PERIOD_MISSING_START_DATE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "004",
        "message": "End date is missing from the duration period.",
        "hint": "Check that the `period` element has a `startDate` child.",
    },
    ErrorCode.DURATION_PERIOD_MISSING_END_DATE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "005",
        "message": "Start date is missing from the duration period.",
        "hint": "Check that the `period` element has an `endDate` child.",
    },
    ErrorCode.DURATION_PERIOD_START_AFTER_END: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "006",
        "message": "Start date '{start_date}' is after end date '{end_date}'.",
        "hint": "Check whether the `period` element has a swapped start and end date..",
    },
    ErrorCode.INVALID_DIMENSION_ATTRIBUTE_VALUE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "007",
        "message": "Invalid dimension attribute value of explicit dimension element: '{dimension}'.",
        "hint": "Check the value of the 'dimension' attribute of the `explicitDimension` element.",
    },
    ErrorCode.INVALID_DIMENSION_MEMBER: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "008",
        "message": "Invalid dimension member '{member}' for explicit dimension {dimension}: '{dimension}'.",
        "hint": "Double check the name of the dimension member.",
    },
    ErrorCode.INVALID_PRECISION_ATTRIBUTE_VALUE: {
        "severity": Severity.WARNING,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "009",
        "message": "Invalid precision attribute value '{precision}'.",
        "hint": "Check the value of the 'precision' attribute of the fact element.",
    },
    ErrorCode.INVALID_DECIMALS_ATTRIBUTE_VALUE: {
        "severity": Severity.WARNING,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "010",
        "message": "Invalid decimals attribute value '{decimals}'.",
        "hint": "Check the value of the 'decimals' attribute of the fact element.",
    },
    ErrorCode.MISSING_FACT_VALUE: {
        "severity": Severity.WARNING,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "010",
        "message": "Fact has no value but the concept {concept} is not nillable",
        "hint": "Check the value of a fact",
    },
    ErrorCode.FACT_UNIT_MISMATCH: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "011",
        "message": "Fact has unit {fact_unit} but should have unit {context_unit}",
        "hint": "Check the unit and the context of the fact",
    },
    ErrorCode.FACT_CONCEPT_MISMATCH: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_INSTANCE,
        "numeric_code": "012",
        "message": "Fact has concept {fact_concept} but should have concept {context_concept}",
        "hint": "Check the concept and the context of the fact",
    },
    ErrorCode.XML_UNIT_ELEMENT_WITHOUT_ONE_CHILD: {
        "severity": Severity.ERROR,
        "area": Area.XML_INSTANCE,
        "numeric_code": "001",
        "message": "Unit with ID '{id}' must have exactly one child element. Found {child_count}.",
        "hint": "Check the children of the unit. Did you add an extra child element?",
    },
    ErrorCode.XML_DIVIDE_ELEMENT_WITHOUT_TWO_CHILDREN: {
        "severity": Severity.ERROR,
        "area": Area.XML_INSTANCE,
        "numeric_code": "002",
        "message": "Divide element of unit with with ID '{id}' must have exactly two children: unitNumerator and unitDenominator. Found {child_count} children, instead.",
        "hint": "Check the children of the divide element. Did you add an extra child  or miss one?",
    },
    ErrorCode.XML_INVALID_DIVIDE_ELEMENT_CHILDREN: {
        "severity": Severity.ERROR,
        "area": Area.XML_INSTANCE,
        "numeric_code": "003",
        "message": "Divide element of unit with ID '{id}' must have exactly two children: unitNumerator and unitDenominator. Found {child_tag} as a child.",
        "hint": "Check the children of the `divide` element. Did you misspell the name of the child?",
    },
    ErrorCode.XML_DUPLICATE_DIVIDE_ELEMENT_CHILDREN: {
        "severity": Severity.ERROR,
        "area": Area.XML_INSTANCE,
        "numeric_code": "004",
        "message": "The unit {id} has a divide element with two children with the same tag: {tag}. One should be 'unitNumerator' and the other 'unitDenominator'",
        "hint": "Check the children of the `divide` element. Did you forget to rename one of the children?",
    },
    ErrorCode.XML_INVALID_UNIT_ELEMENT_CHILDREN: {
        "severity": Severity.ERROR,
        "area": Area.XML_INSTANCE,
        "numeric_code": "005",
        "message": "Unit with ID '{id}' must have exactly one child element: 'measrue' or 'divide'. Found {child_tag} as a child.",
        "hint": "Check the child of the unit. Did you misspell the name of the child?",
    },
    ErrorCode.XML_MISSING_UNIT_MEASURE: {
        "severity": Severity.ERROR,
        "area": Area.XML_INSTANCE,
        "numeric_code": "006",
        "message": "Unit measure element cannot be empty.",
        "hint": "Check the unit measure. Did you misplace the text?",
    },
    # GENERAL: 000 - 099
    ErrorCode.IXBRL_DUPLICATE_ELEMENT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "001",
        "message": "ID '{id}' has already been used.",
        "hint": "Check for duplicate IDs in the instance document set.",
    },
    ErrorCode.IXBRL_ELEMENT_NOT_SUPPORTED: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "002",
        "message": "Element '{tag}' is not yet supported. Ignoring for now.",
        "hint": None,  # type: ignore
    },
    # HEADER: 100 - 199
    ErrorCode.IXBRL_HEADER_ELEMENT_IN_HEAD: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "100",
        "message": "The ix:header element is not allowed in the head element.",
        "hint": "Move ix:header element to the body.",
    },
    ErrorCode.IXBRL_INVALID_HEADER_CHILD: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "101",
        "message": "The ix:header element must have one of the following children: ix:hidden, ix:resources, ix:references. Found {child_tag}.",
        "hint": "Check for a misspelling in the child element.",
    },
    ErrorCode.IXBRL_MORE_THAN_ONE_HIDDEN_HEADER_CHILD: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "102",
        "message": "The ix:header element can have at most 1 ix:hidden element. Found {count}",
        "hint": "Check the ix:header element.",
    },
    ErrorCode.IXBRL_MORE_THAN_ONE_RESOURCES_HEADER_CHILD: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "103",
        "message": "The ix:header element can have at most 1 ix:resources element. Found {count}",
        "hint": "Check the ix:header element.",
    },
    ErrorCode.IXBRL_NO_HEADER_ELEMENTS: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "104",
        "message": "The IXBRL Document Set must have at least one ix:header element but 0 were found.",
        "hint": "Insert an ix:header element.",
    },
    # REFERENCES: 200 - 299
    ErrorCode.IXBRL_REFERENCES_ELEMENT_WITHOUT_CHILDREN: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "200",
        "message": "The ix:references element must have at least one child element.",
        "hint": "Check the ix:references element.",
    },
    ErrorCode.IXBRL_INVALID_REFERENCES_CHILD: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "201",
        "message": "The ix:references element must have one of the following children: link:schemaRef, link:linkbaseRef. Found {children}.",
        "hint": "Check for a misspelling in the child element.",
    },
    # RESOURCES: 300 - 399
    ErrorCode.IXBRL_NO_RESOURCES_ELEMENTS: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "300",
        "message": "The IXBRL Document Set must have at least one ix:resources element but 0 were found.",
        "hint": "Insert an ix:resources element inside of a ix:header element.",
    },
    ErrorCode.IXBRL_INVALID_RESOURCES_CHILD: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "301",
        "message": "The ix:resources element must have one of the following children: link:roleRef, link:arcroleRef, xbrli:context, xbrli:unit. Found {child_tag}.",
        "hint": "Check for a misspelling in the child element.",
    },
    ErrorCode.IXBRL_CONTEXT_WITHOUT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "360",
        "message": "Context does not have an id",
        "hint": "Set the ID attribute of the context.",
    },
    ErrorCode.IXBRL_UNIT_WITHOUT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "380",
        "message": "Unit does not have an id",
        "hint": "Set the ID attribute of the unit.",
    },
    ErrorCode.IXBRL_INVALID_HIDDEN_ELEMENT: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "400",
        "message": "The ix:hidden element must have one of the following children: link:roleRef, link:arcroleRef, xbrli:context, xbrli:unit. Found {child_tag}.",
        "hint": "Check for a misspelling in the children element.",
    },
    ErrorCode.IXBRL_FACT_WITHOUT_CONTEXT: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "500",
        "message": "Fact with id {fact_id} does not have a context",
        "hint": "Check the `contextRef` attribute of the fact.",
    },
    ErrorCode.IXBRL_INVALID_FACT_CONTEXT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "501",
        "message": "Context {context_id} is not valid.",
        "hint": "Check the `contextRef` attribute of the corresponding fact.",
    },
    ErrorCode.IXBRL_INVALID_FACT_UNIT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "502",
        "message": "Unit {unit_id} for fact {fact_id} is not a valid.",
        "hint": "Check the `unitRef` attribute of the corresponding fact.",
    },
    ErrorCode.IXBRL_FACT_WITHOUT_CONCEPT_NAME: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "503",
        "message": "Fact with id {fact_id} does not have a concept name",
        "hint": "Check the `name` attribute of the fact.",
    },
    ErrorCode.IXBRL_FACT_INVALID_CONCEPT: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "504",
        "message": "Fact with id {fact_id} uses an invalid concept name '{concept_name}'",
        "hint": "Check the `name` attribute of the fact.",
    },
    ErrorCode.IXBRL_NON_FRACTION_WITHOUT_UNIT: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "505",
        "message": "ix:nonFraction fact with id {fact_id} does not have a unit.",
        "hint": "Check the `unitRef` attribute of the fact.",
    },
    ErrorCode.IXBRL_MUTUALLY_EXCLUSIVE_ATTRIBUTES_IN_NON_FRACTION: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "506",
        "message": "Non-fraction fact cannot have more than one of: decimals, precision and xsi_nil attribute. Got more than one.",
        "hint": "Remove one of the attributes",
    },
    ErrorCode.IXBRL_BOTH_TEXT_AND_CHILDREN_IN_NON_FRACTION: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "507",
        "message": "Non-fraction fact cannot have both text and children. Got both.",
        "hint": "Remove the text or the children from the non-fraction element",
    },
    ErrorCode.IXBRL_TEXT_OR_CHILDREN_WITH_NIL: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "508",
        "message": "Non-fraction fact cannot have both text and children when its xsi:nil attribute is set to true.",
        "hint": "Remove either the xsi:nil attribute or the text or the children from the non-fraction element",
    },
    ErrorCode.IXBRL_NO_TEXT_OR_CHILDREN_WITH_ABSENT_NIL_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "509",
        "message": "Non-fraction fact must have either text or children when its xsi:nil attribute is not set to true.",
        "hint": "Set the xsi:nil attribute to true or add text or children to the non-fraction element",
    },
    ErrorCode.IXBRL_INVALID_SIGN_ATTRIBUTE_VALUE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "510",
        "message": "Sign attribute value '{sign}' is not valid. If set, it should always be set to '-'.",
        "hint": "Check the value of the sign attribute.",
    },
    ErrorCode.IXBRL_MULTIPLE_NON_FRACTION_CHILDREN: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "511",
        "message": "Non-fraction fact has more than one child element. Using the first child.",
        "hint": "Check the children of the non-fraction element.",
    },
    ErrorCode.IXBRL_INVALID_NON_FRACTION_CHILD: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "512",
        "message": "Non-fraction facts can only have 1 non-fraction element as a child. Found {child_tag}.",
        "hint": "Check the children of the non-fraction element.",
    },
    ErrorCode.IXBRL_NON_NUMERICAL_NON_FRACTION_FACT_VALUE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "513",
        "message": "Non-fraction fact has a non-numeric value '{value}'.",
        "hint": "Check the value of the fact.",
    },
    ErrorCode.IXBRL_NEGATIVE_NON_FRACTION_FACT_VALUE: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "514",
        "message": "Non-fraction has a negative value '{value}'. This is not  allowed.",
        "hint": "Check the value of the fact.",
    },
    ErrorCode.IXBRL_NIL_ATTRIBUTE_IN_NON_FRACTION_CHILD: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "515",
        "message": "Non-fraction child of another non-fraction element has its nil attribute set to 'true'. This is not allowed.'.",
        "hint": "Remove the xsi:nil attribute from the child element.",
    },
    ErrorCode.IXBRL_DIFFERING_FORMAT_SCALE_OR_UNIT_FOR_NON_FRACTION_CHILD: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "516",
        "message": "Non-fraction child of another non-fraction element has a different format, scale or unit.\n"
        + "Parent has the following format, scale and unit {parent_format}, {parent_scale}, {parent_unit}.\n"
        + "The child has the following format, scale and unit: {this_format}, {this_scale}, {this_unit}",
        "hint": "Check the attributes of the child and parent element.",
    },
    ErrorCode.IXBRL_INVALID_NON_NUMERIC_FACT_ESCAPE_ATTRIBUTE_VALUE: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "530",
        "message": "Non-numeric fact has an invalid escape attribute value '{value}'. Assuming it is set to 'true'",
        "hint": "Check the value of the escape attribute.",
    },
    ErrorCode.IXBRL_CONTINUATION_WITHOUT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "540",
        "message": "Continuation element has no id attribute.",
        "hint": "Add an id attribute to the continuation element.",
    },
    ErrorCode.IXBRL_REUSED_CONTINUATION: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "541",
        "message": "The continuation element with id '{id}' has already been used. Trying to use it again in continuation chain of element with id '{element_id}'.",
        "hint": "Look at the referencing ids of the fact or continuation elements using this ID.",
    },
    ErrorCode.IXBRL_INVALID_CONTINUATION_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "542",
        "message": "ID '{id}' in the continuation chain of the fact or footnote with id '{element_id}' does not exist.",
        "hint": "Look at the referencing ids of the fact or continuation elements in this chain.",
    },
    ErrorCode.IXBRL_INVALID_DESCENDANT_IN_CONTINUATION_CHAIN: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "543",
        "message": "In a continuation chain, no element can be a descendant of another element in that same chain. Element with id '{descendant_id}' is"
        + "a descendant of element with id '{parent_id}', but they are part of the same continuation chain.",
        "hint": "Look at the elements of the chain closely.",
    },
    ErrorCode.IXBRL_UNUSED_CONTINUATION_ELEMENTS: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "544",
        "message": "Continuation elements with the following IDs {element_ids} were unused.",
        "hint": "Have you declared any unnecessary continuation elements?",
    },
    ErrorCode.IXBRL_FOOTNOTE_WITHOUT_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "550",
        "message": "Footnote element has no id attribute.",
        "hint": "Add an id attribute to the footnote element.",
    },
    ErrorCode.IXBRL_INVALID_FOOTNOTE_ROLE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "551",
        "message": "Footnote element with id {id} has an invalid URI for its footnoteRole attribute '{role}'.",
        "hint": "Check the value of the footnoteRole attribute.",
    },
    ErrorCode.IXBRL_FOOTNOTE_WITHOUT_LANGUAGE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "552",
        "message": "Footnote element with id {id} has no xml:lang attribute in scope.",
        "hint": "Add an xml:lang attribute to the footnote or ascendant elements.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_WITHOUT_FROMREFS: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "560",
        "message": "Relationship element has no fromRefs attribute.",
        "hint": "Add a fromRefs attribute to the relationship element.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_WITHOUT_TOREFS: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "561",
        "message": "Relationship element has no toRefs attribute.",
        "hint": "Add a toRefs attribute to the relationship element.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_REPEATED_ID: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "562",
        "message": "A token in the fromRefs attribute of the relationship element is reused in its toRefs attribute.",
        "hint": "Check the values of the fromRefs and toRefs attributes.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_FACT_ID_IN_FROMREFS: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "563",
        "message": "The following IDs in the fromRefs attribute of the relationship element do not point to a fact: {invalid_ids}.",
        "hint": "Double-check the IDs.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_FACT_OR_FOOTNOTE_ID_IN_TOREFS: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "564",
        "message": "The following IDs in the toRefs attribute of the relationship element do not point to a fact or a footnote: {invalid_ids}.",
        "hint": "Double-check the IDs.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_MIXED_FACT_AND_FOOTNOTES_IN_TOREFS: {
        "severity": Severity.WARNING,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "565",
        "message": "The toRefs attribute of the relationship element contains a mix of facts and footnotes. This is not allowed.",
        "hint": "Check the values of the toRefs attribute.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_ARCROLE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "566",
        "message": "Relationship element has an invalid arcrole attribute '{arcrole}'. The arcrole must be a valid URI",
        "hint": "Check the value of the arcrole attribute.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_LINKROLE: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "567",
        "message": "Relationship element has an invalid linkrole attribute '{linkrole}'. The linkrole must be a valid URI",
        "hint": "Check the value of the linkrole attribute.",
    },
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_ORDER: {
        "severity": Severity.ERROR,
        "area": Area.IXBRL_INSTANCE,
        "numeric_code": "568",
        "message": "Relationship element has an invalid order attribute '{order}'. The order must be a valid floating-point number.",
        "hint": "Check the value of the order attribute. Maybe you've used a ',' instead of a '.'?",
    },
    # General Linkbase
    ErrorCode.ROLEREF_INVALID_LINKTYPE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_LINKBASE,
        "numeric_code": "100",
        "message": "The link:(arc)roleRef element has an invalid xlink:linktype attribute '{linktype}'. This must always be set to 'simple'",
        "hint": "Set the xlink:linktype attribute to 'simple'.",
    },
    ErrorCode.ROLEREF_MISSING_HREF_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_LINKBASE,
        "numeric_code": "101",
        "message": "The link:(arc)roleRef element has a missing xlink:href attribute.",
        "hint": "Add an xlink:href attribute.",
    },
    ErrorCode.ROLEREF_INVALID_HREF_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_LINKBASE,
        "numeric_code": "102",
        "message": "The link:(arc)roleRef element has an invalid xlink:href attribute '{href}'. It should always be a valid URI.",
        "hint": "Check the value of the xlink:href attribute.",
    },
    ErrorCode.ROLEREF_MISSING_ROLE_URI_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_LINKBASE,
        "numeric_code": "103",
        "message": "The link:(arc)roleRef element has a missing roleURI attribute.",
        "hint": "Add a roleURI attribute.",
    },
    ErrorCode.ROLEREF_INVALID_ROLE_URI_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_LINKBASE,
        "numeric_code": "104",
        "message": "The link:(arc)roleRef element has an invalid roleURI attribute '{role_uri}'. It should always be a valid URI.",
        "hint": "Check the value of the roleURI attribute.",
    },
    ErrorCode.ROLEREF_EMPTY_ROLE_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.GENERAL_LINKBASE,
        "numeric_code": "105",
        "message": "If the xlink:role attribute is present in a link:(arc)roleRef element, it must not be empty.",
        "hint": "Either remove or fill in the xlink:role attribute.",
    },
    # Taxonomy package
    ErrorCode.INVALID_CATALOG_ROOT_NODE: {
        "severity": Severity.ERROR,
        "area": Area.TAXONOMY_PACKAGE,
        "numeric_code": "000",
        "message": "The root node of the catalog should be a <{{urn:oasis:names:tc:entity:xmlns:xml:catalog}}catalog> element.",
        "hint": "Check the root node of the catalog and its namespace.",
        "xbrl_error_code": QName(error_namespaces["tpe"], "tpe", "invalidCatalogFile"),
    },
    ErrorCode.REWRITE_URI_MISSING_ATTRIBUTE: {
        "severity": Severity.ERROR,
        "area": Area.TAXONOMY_PACKAGE,
        "numeric_code": "001",
        "message": "The rewriteURI element is missing either a 'uriStaratString' or a 'rewritePrefix' attribute.",
        "hint": "Check the attributes of the rewriteURI element.",
        "xbrl_error_code": QName(error_namespaces["tpe"], "tpe", "invalidCatalogFile"),
    },
    ErrorCode.MULTIPLE_REWRITE_URIS_FOR_START_STRING: {
        "severity": Severity.ERROR,
        "area": Area.TAXONOMY_PACKAGE,
        "numeric_code": "002",
        "message": "The catalog contains multiple rewriteURI elements with equivalent 'uriStartString' URIs: {uri}",
        "hint": "Check the rewriteURI elements for typos or duplication.",
        "xbrl_error_code": QName(
            error_namespaces["tpe"], "tpe", "multipleRewriteURIsForStartString"
        ),
    },
    # Validation
    ErrorCode.MULTIPLE_PRESENTATION_NETWORKS_IN_COMPONENT: {
        "severity": Severity.WARNING,
        "area": Area.VALIDATION,
        "numeric_code": "000",
        "message": "Component {linkrole_uri} has more than one presentation network.",
        "hint": "Check the linkroles of the networks in the component",
    },
    ErrorCode.MULTIPLE_CALCULATION_NETWORKS_IN_COMPONENT: {
        "severity": Severity.WARNING,
        "area": Area.VALIDATION,
        "numeric_code": "001",
        "message": "Component {linkrole_uri} has more than one calculation network.",
        "hint": "Check the linkroles of the networks in the component",
    },
    ErrorCode.MULTIPLE_DEFINITION_NETWORKS_IN_COMPONENT: {
        "severity": Severity.WARNING,
        "area": Area.VALIDATION,
        "numeric_code": "002",
        "message": "Component {linkrole_uri} has more than one definition network.",
        "hint": "Check the linkroles of the networks in the component",
    },
    # Schema
    ErrorCode.PRESENTATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT: {
        "severity": Severity.WARNING,
        "area": Area.SCHEMA_DEFINITION,
        "numeric_code": "000",
        "message": "Component {linkrole_uri} has a presentation network but without an appropriate usedOn element in its schema.",
        "hint": "Add a `<link:usedOn>link:presentationLink</link:usedOn>` element in the component.",
    },
    ErrorCode.CALCULATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT: {
        "severity": Severity.WARNING,
        "area": Area.SCHEMA_DEFINITION,
        "numeric_code": "001",
        "message": "Component {linkrole_uri} has a calculation network but without an appropriate usedOn element in its schema.",
        "hint": "Add a `<link:usedOn>link:calculationLink</link:usedOn>` element in the component.",
    },
    ErrorCode.DEFINITION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT: {
        "severity": Severity.WARNING,
        "area": Area.SCHEMA_DEFINITION,
        "numeric_code": "002",
        "message": "Component {linkrole_uri} has a definition network but without an appropriate usedOn element in its schema.",
        "hint": "Add a `<link:usedOn>link:definitionLink</link:usedOn>` element in the component.",
    },
    # Misc
    ErrorCode.QNAME_NAMESPACE_NOT_IN_ELEMENT_SCOPE: {
        "severity": Severity.ERROR,
        "area": Area.MISC,
        "numeric_code": "000",
        "message": "QName namespace '{namespace}' is not in element scope",
        "hint": "Check for a misspelling in the QName's prefix",
    },
    ErrorCode.QNAME_MISSING_NAMESPACE: {
        "severity": Severity.ERROR,
        "area": Area.MISC,
        "numeric_code": "001",
        "message": "QName '{local_name}' is missing a namespace (and a default one is not provided)",
        "hint": "Did you forget the prefix of the local name?",
    },
}
