from typing import Any, Callable, Dict

from brel.errors.area import Area
from brel.errors.error_code import ErrorCode
from brel.errors.error_instance import ErrorInstance
from brel.errors.severity import Severity
from brel.qnames.qname import QName

error_namespaces = {"tpe": "http://xbrl.org/2016/taxonomy-package/errors"}

error_factory_registry: Dict[ErrorCode, Callable[[], ErrorInstance]] = {
    ErrorCode.MISSING_CONTEXT_PERIOD: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "000",
        "Context is missing a period child element",
        "Check the definition of the context.",
    ),
    ErrorCode.MISSING_CONTEXT_ENTITY: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "001",
        "Context is missing an entity child element",
        "Check the definition of the context.",
    ),
    ErrorCode.INVALID_DIMENSION_TYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "002",
        "Dimension type '{dimension_type}' is not valid. It should either be 'explicitMember' or typedMember'.",
        "Check the segment part of the context.",
    ),
    ErrorCode.INVALID_CONTEXT_PERIOD_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "003",
        "Date '{date}' is not a valid date.",
        "Check the text contents of the <period> element. Dates should be in the ISO 8601 format (YYYY-MM-DD).",
    ),
    ErrorCode.DURATION_PERIOD_MISSING_START_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "004",
        "End date is missing from the duration period.",
        "Check that the `period` element has a `startDate` child.",
    ),
    ErrorCode.DURATION_PERIOD_MISSING_END_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "005",
        "Start date is missing from the duration period.",
        "Check that the `period` element has an `endDate` child.",
    ),
    ErrorCode.DURATION_PERIOD_START_AFTER_END: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "006",
        "Start date '{start_date}' is after end date '{end_date}'.",
        "Check whether the `period` element has a swapped start and end date..",
    ),
    ErrorCode.ENTITY_MISSING_IDENTIFIER_ELEMENT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "007",
        "The entity element is missing an identifier child element",
        "Check the definition of the entity.",
    ),
    ErrorCode.ENTITY_IDENTIFIER_MISSING_SCHEME: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "008",
        "The identifier element is missing a scheme attribute",
        "Check the definition of the identifier.",
    ),
    ErrorCode.ENTITY_IDENTIFIER_MISSING_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "009",
        "The entity identifier element is missing its value.",
        "Check the text of the identifier element. It should not be empty.",
    ),
    ErrorCode.INVALID_EXPLICIT_DIMENSION_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "010",
        "Invalid dimension value of explicit dimension element: '{dimension}'.",
        "Check the value of the 'dimension' attribute of the `explicitDimension` element.",
    ),
    ErrorCode.MISSING_EXPLICIT_DIMENSION_MEMBER: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "011",
        "Missing dimension member for explicit dimension '{dimension}'.",
        "Please enclose the name of the dimension member in the `explicitMember` element.",
    ),
    ErrorCode.INVALID_EXPLICIT_DIMENSION_MEMBER: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "012",
        "Invalid dimension member '{member}' for explicit dimension '{dimension}'.",
        "Double check the name of the dimension member.",
    ),
    ErrorCode.INVALID_TYPED_DIMENSION_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "013",
        "Invalid dimension value of typed dimension element: '{dimension}'.",
        "Check the value of the 'dimension' attribute of the `typedDimension` element.",
    ),
    ErrorCode.MULTIPLE_TYPED_DIMENSION_ELEMENT_CHILDREN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "014",
        "Typed dimension element '{dimension}' has more than one child element.",
        "Check the children of the typed dimension element.",
    ),
    ErrorCode.NO_TYPED_DIMENSION_ELEMENT_CHILDREN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "015",
        "Typed dimension element '{dimension}' has no children but should have exactly one child",
        "Check the children of the typed dimension element.",
    ),
    ErrorCode.MISSING_TYPED_DIMENSION_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "016",
        "There is no value provided for the typed dimension {dimension}.",
        "Check the text inside of the typed dimension element.",
    ),
    ErrorCode.INVALID_PRECISION_ATTRIBUTE_VALUE: lambda: ErrorInstance(
        Severity.WARNING,
        Area.GENERAL_INSTANCE,
        "017",
        "Invalid precision attribute value '{precision}'.",
        "Check the value of the 'precision' attribute of the fact element.",
    ),
    ErrorCode.INVALID_DECIMALS_ATTRIBUTE_VALUE: lambda: ErrorInstance(
        Severity.WARNING,
        Area.GENERAL_INSTANCE,
        "018",
        "Invalid decimals attribute value '{decimals}'.",
        "Check the value of the 'decimals' attribute of the fact element.",
    ),
    ErrorCode.MISSING_FACT_VALUE: lambda: ErrorInstance(
        Severity.WARNING,
        Area.GENERAL_INSTANCE,
        "019",
        "Fact has no value but the concept {concept} is not nillable",
        "Check the value of a fact",
    ),
    ErrorCode.FACT_UNIT_MISMATCH: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "020",
        "Fact has unit {fact_unit} but should have unit {context_unit}",
        "Check the unit and the context of the fact",
    ),
    ErrorCode.FACT_CONCEPT_MISMATCH: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_INSTANCE,
        "021",
        "Fact has concept {fact_concept} but should have concept {context_concept}",
        "Check the concept and the context of the fact",
    ),
    ErrorCode.XML_UNIT_ELEMENT_WITHOUT_ONE_CHILD: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "001",
        "Unit with ID '{id}' must have exactly one child element. Found {child_count}.",
        "Check the children of the unit. Did you add an extra child element?",
    ),
    ErrorCode.XML_DIVIDE_ELEMENT_WITHOUT_TWO_CHILDREN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "002",
        "Divide element of unit with with ID '{id}' must have exactly two children: unitNumerator and unitDenominator. Found {child_count} children, instead.",
        "Check the children of the divide element. Did you add an extra child  or miss one?",
    ),
    ErrorCode.XML_INVALID_DIVIDE_ELEMENT_CHILDREN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "003",
        "Divide element of unit with ID '{id}' must have exactly two children: unitNumerator and unitDenominator. Found {child_tag} as a child.",
        "Check the children of the `divide` element. Did you misspell the name of the child?",
    ),
    ErrorCode.XML_DUPLICATE_DIVIDE_ELEMENT_CHILDREN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "004",
        "The unit {id} has a divide element with two children with the same tag: lambda: ErrorInstance(tag}. One should be 'unitNumerator' and the other 'unitDenominator'",
        "Check the children of the `divide` element. Did you forget to rename one of the children?",
    ),
    ErrorCode.XML_INVALID_UNIT_ELEMENT_CHILDREN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "005",
        "Unit with ID '{id}' must have exactly one child element: 'measrue' or 'divide'. Found {child_tag} as a child.",
        "Check the child of the unit. Did you misspell the name of the child?",
    ),
    ErrorCode.XML_MISSING_UNIT_MEASURE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "006",
        "Unit measure element cannot be empty.",
        "Check the unit measure. Did you misplace the text?",
    ),
    ErrorCode.XML_FACT_INVALID_CONCEPT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "100",
        "Concept name {concept_name} is invalid.",
        "Check the tag of the fact element for misspelling.",
    ),
    ErrorCode.XML_INVALID_FACT_CONTEXT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "101",
        "Context ID {context_id} is not valid.",
        "Check the `contextRef` attribute of the corresponding fact.",
    ),
    ErrorCode.XML_INVALID_FACT_CONTEXT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.XML_INSTANCE,
        "102",
        "Unit ID {unit_id} is not a valid.",
        "Check the `unitRef` attribute of the corresponding fact.",
    ),
    # GENERAL: 000 - 099
    ErrorCode.IXBRL_DUPLICATE_ELEMENT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "001",
        "ID '{id}' has already been used.",
        "Check for duplicate IDs in the instance document set.",
    ),
    ErrorCode.IXBRL_ELEMENT_NOT_SUPPORTED: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "002",
        "Element '{tag}' is not yet supported. Ignoring for now.",
        None,  # type: ignore
    ),
    # HEADER: 100 - 199
    ErrorCode.IXBRL_HEADER_ELEMENT_IN_HEAD: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "100",
        "The ix:header element is not allowed in the head element.",
        "Move ix:header element to the body.",
    ),
    ErrorCode.IXBRL_INVALID_HEADER_CHILD: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "101",
        "The ix:header element must have one of the following children: ix:hidden, ix:resources, ix:references. Found {child_tag}.",
        "Check for a misspelling in the child element.",
    ),
    ErrorCode.IXBRL_MORE_THAN_ONE_HIDDEN_HEADER_CHILD: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "102",
        "The ix:header element can have at most 1 ix:hidden element. Found {count}",
        "Check the ix:header element.",
    ),
    ErrorCode.IXBRL_MORE_THAN_ONE_RESOURCES_HEADER_CHILD: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "103",
        "The ix:header element can have at most 1 ix:resources element. Found {count}",
        "Check the ix:header element.",
    ),
    ErrorCode.IXBRL_NO_HEADER_ELEMENTS: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "104",
        "The IXBRL Document Set must have at least one ix:header element but 0 were found.",
        "Insert an ix:header element.",
    ),
    # REFERENCES: 200 - 299
    ErrorCode.IXBRL_REFERENCES_ELEMENT_WITHOUT_CHILDREN: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "200",
        "The ix:references element must have at least one child element.",
        "Check the ix:references element.",
    ),
    ErrorCode.IXBRL_INVALID_REFERENCES_CHILD: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "201",
        "The ix:references element must have one of the following children: link:schemaRef, link:linkbaseRef. Found {children}.",
        "Check for a misspelling in the child element.",
    ),
    # RESOURCES: 300 - 399
    ErrorCode.IXBRL_NO_RESOURCES_ELEMENTS: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "300",
        "The IXBRL Document Set must have at least one ix:resources element but 0 were found.",
        "Insert an ix:resources element inside of a ix:header element.",
    ),
    ErrorCode.IXBRL_INVALID_RESOURCES_CHILD: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "301",
        "The ix:resources element must have one of the following children: link:roleRef, link:arcroleRef, xbrli:context, xbrli:unit. Found {child_tag}.",
        "Check for a misspelling in the child element.",
    ),
    ErrorCode.IXBRL_CONTEXT_WITHOUT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "360",
        "Context does not have an id",
        "Set the ID attribute of the context.",
    ),
    ErrorCode.IXBRL_UNIT_WITHOUT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "380",
        "Unit does not have an id",
        "Set the ID attribute of the unit.",
    ),
    ErrorCode.IXBRL_INVALID_HIDDEN_ELEMENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "400",
        "The ix:hidden element must have one of the following children: link:roleRef, link:arcroleRef, xbrli:context, xbrli:unit. Found {child_tag}.",
        "Check for a misspelling in the children element.",
    ),
    ErrorCode.IXBRL_FACT_WITHOUT_CONTEXT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "500",
        "Fact with id {fact_id} does not have a context",
        "Check the `contextRef` attribute of the fact.",
    ),
    ErrorCode.IXBRL_INVALID_FACT_CONTEXT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "501",
        "Context {context_id} is not valid.",
        "Check the `contextRef` attribute of the corresponding fact.",
    ),
    ErrorCode.IXBRL_INVALID_FACT_UNIT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "502",
        "Unit {unit_id} for fact {fact_id} is not a valid.",
        "Check the `unitRef` attribute of the corresponding fact.",
    ),
    ErrorCode.IXBRL_FACT_WITHOUT_CONCEPT_NAME: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "503",
        "Fact with id {fact_id} does not have a concept name",
        "Check the `name` attribute of the fact.",
    ),
    ErrorCode.IXBRL_FACT_INVALID_CONCEPT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "504",
        "Fact with id {fact_id} uses an invalid concept name '{concept_name}'",
        "Check the `name` attribute of the fact.",
    ),
    ErrorCode.IXBRL_NON_FRACTION_WITHOUT_UNIT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "505",
        "ix:nonFraction fact with id {fact_id} does not have a unit.",
        "Check the `unitRef` attribute of the fact.",
    ),
    ErrorCode.IXBRL_MUTUALLY_EXCLUSIVE_ATTRIBUTES_IN_NON_FRACTION: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "506",
        "Non-fraction fact cannot have more than one of: decimals, precision and xsi_nil attribute. Got more than one.",
        "Remove one of the attributes",
    ),
    ErrorCode.IXBRL_BOTH_TEXT_AND_CHILDREN_IN_NON_FRACTION: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "507",
        "Non-fraction fact cannot have both text and children. Got both.",
        "Remove the text or the children from the non-fraction element",
    ),
    ErrorCode.IXBRL_TEXT_OR_CHILDREN_WITH_NIL: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "508",
        "Non-fraction fact cannot have both text and children when its xsi:nil attribute is set to true.",
        "Remove either the xsi:nil attribute or the text or the children from the non-fraction element",
    ),
    ErrorCode.IXBRL_NO_TEXT_OR_CHILDREN_WITH_ABSENT_NIL_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "509",
        "Non-fraction fact must have either text or children when its xsi:nil attribute is not set to true.",
        "Set the xsi:nil attribute to true or add text or children to the non-fraction element",
    ),
    ErrorCode.IXBRL_INVALID_SIGN_ATTRIBUTE_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "510",
        "Sign attribute value '{sign}' is not valid. If set, it should always be set to '-'.",
        "Check the value of the sign attribute.",
    ),
    ErrorCode.IXBRL_MULTIPLE_NON_FRACTION_CHILDREN: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "511",
        "Non-fraction fact has more than one child element. Using the first child.",
        "Check the children of the non-fraction element.",
    ),
    ErrorCode.IXBRL_INVALID_NON_FRACTION_CHILD: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "512",
        "Non-fraction facts can only have 1 non-fraction element as a child. Found {child_tag}.",
        "Check the children of the non-fraction element.",
    ),
    ErrorCode.IXBRL_NON_NUMERICAL_NON_FRACTION_FACT_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "513",
        "Non-fraction fact has a non-numeric value '{value}'.",
        "Check the value of the fact.",
    ),
    ErrorCode.IXBRL_NEGATIVE_NON_FRACTION_FACT_VALUE: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "514",
        "Non-fraction has a negative value '{value}'. This is not  allowed.",
        "Check the value of the fact.",
    ),
    ErrorCode.IXBRL_NIL_ATTRIBUTE_IN_NON_FRACTION_CHILD: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "515",
        "Non-fraction child of another non-fraction element has its nil attribute set to 'true'. This is not allowed.'.",
        "Remove the xsi:nil attribute from the child element.",
    ),
    ErrorCode.IXBRL_DIFFERING_FORMAT_SCALE_OR_UNIT_FOR_NON_FRACTION_CHILD: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "516",
        "Non-fraction child of another non-fraction element has a different format, scale or unit.\n"
        + "Parent has the following format, scale and unit {parent_format), {parent_scale), {parent_unit}.\n"
        + "The child has the following format, scale and unit: lambda: ErrorInstance(this_format), {this_scale), {this_unit}",
        "Check the attributes of the child and parent element.",
    ),
    ErrorCode.IXBRL_INVALID_NON_NUMERIC_FACT_ESCAPE_ATTRIBUTE_VALUE: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "530",
        "Non-numeric fact has an invalid escape attribute value '{value}'. Assuming it is set to 'true'",
        "Check the value of the escape attribute.",
    ),
    ErrorCode.IXBRL_CONTINUATION_WITHOUT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "540",
        "Continuation element has no id attribute.",
        "Add an id attribute to the continuation element.",
    ),
    ErrorCode.IXBRL_REUSED_CONTINUATION: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "541",
        "The continuation element with id '{id}' has already been used. Trying to use it again in continuation chain of element with id '{element_id}'.",
        "Look at the referencing ids of the fact or continuation elements using this ID.",
    ),
    ErrorCode.IXBRL_INVALID_CONTINUATION_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "542",
        "ID '{id}' in the continuation chain of the fact or footnote with id '{element_id}' does not exist.",
        "Look at the referencing ids of the fact or continuation elements in this chain.",
    ),
    ErrorCode.IXBRL_INVALID_DESCENDANT_IN_CONTINUATION_CHAIN: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "543",
        "In a continuation chain, no element can be a descendant of another element in that same chain. Element with id '{descendant_id}' is"
        + "a descendant of element with id '{parent_id}', but they are part of the same continuation chain.",
        "Look at the elements of the chain closely.",
    ),
    ErrorCode.IXBRL_UNUSED_CONTINUATION_ELEMENTS: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "544",
        "Continuation elements with the following IDs {element_ids} were unused.",
        "Have you declared any unnecessary continuation elements?",
    ),
    ErrorCode.IXBRL_FOOTNOTE_WITHOUT_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "550",
        "Footnote element has no id attribute.",
        "Add an id attribute to the footnote element.",
    ),
    ErrorCode.IXBRL_INVALID_FOOTNOTE_ROLE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "551",
        "Footnote element with id {id} has an invalid URI for its footnoteRole attribute '{role}'.",
        "Check the value of the footnoteRole attribute.",
    ),
    ErrorCode.IXBRL_FOOTNOTE_WITHOUT_LANGUAGE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "552",
        "Footnote element with id {id} has no xml:lang attribute in scope.",
        "Add an xml:lang attribute to the footnote or ascendant elements.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_WITHOUT_FROMREFS: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "560",
        "Relationship element has no fromRefs attribute.",
        "Add a fromRefs attribute to the relationship element.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_WITHOUT_TOREFS: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "561",
        "Relationship element has no toRefs attribute.",
        "Add a toRefs attribute to the relationship element.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_REPEATED_ID: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "562",
        "A token in the fromRefs attribute of the relationship element is reused in its toRefs attribute.",
        "Check the values of the fromRefs and toRefs attributes.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_FACT_ID_IN_FROMREFS: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "563",
        "The following IDs in the fromRefs attribute of the relationship element do not point to a fact: {invalid_ids}.",
        "Double-check the IDs.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_FACT_OR_FOOTNOTE_ID_IN_TOREFS: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "564",
        "The following IDs in the toRefs attribute of the relationship element do not point to a fact or a footnote: {invalid_ids}.",
        "Double-check the IDs.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_MIXED_FACT_AND_FOOTNOTES_IN_TOREFS: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "565",
        "The toRefs attribute of the relationship element contains a mix of facts and footnotes. This is not allowed.",
        "Check the values of the toRefs attribute.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_ARCROLE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "566",
        "Relationship element has an invalid arcrole attribute '{arcrole}'. The arcrole must be a valid URI",
        "Check the value of the arcrole attribute.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_LINKROLE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "567",
        "Relationship element has an invalid linkrole attribute '{linkrole}'. The linkrole must be a valid URI",
        "Check the value of the linkrole attribute.",
    ),
    ErrorCode.IXBRL_RELATIONSHIP_INVALID_ORDER: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "568",
        "Relationship element has an invalid order attribute '{order}'. The order must be a valid floating-point number.",
        "Check the value of the order attribute. Maybe you've used a ',' instead of a '.'?",
    ),
    ErrorCode.UNSUPPORTED_DATE_FORMAT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "600",
        "Unknown date format '{format}'.",
        "Check the value of the `format` attribute.",
    ),
    ErrorCode.DATE_DOES_NOT_MATCH_EXPECTED_FORMAT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "601",
        "Date '{date}' does not match the expected format '{format}'.",
        "Check the value of the `date` attribute.",
    ),
    ErrorCode.YEAR_PRESENT_IN_RECURRING_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "602",
        "Year should not be present in recurring date: '{date}'.",
        "Check the value of the text in the element.",
    ),
    ErrorCode.MONTH_OR_DAY_NOT_PRESENT_IN_RECURRING_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "603",
        "Month and day should both be present in recurring date: '{date}'.",
        "Check the value of the text in the element.",
    ),
    ErrorCode.YEAR_OR_MONTH_NOT_PRESENT_IN_NON_RECURRING_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "604",
        "Year and month should both be present in non-recurring date: '{date}'.",
        "Check the value of the text in the element.",
    ),
    ErrorCode.DAY_NOT_PRESENT_IN_FULL_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "605",
        "Day should be present in full date: '{date}'.",
        "Check the value of the text in the element.",
    ),
    ErrorCode.INVALID_GREGORIAN_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "606",
        "Invalid gregorian date: '{date}'.",
        "Check the value of the text in the element.",
    ),
    ErrorCode.INVALID_JAPANESE_IMPERIAL_DATE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "607",
        "Invalid Japanese imperial date: '{date}'. Out of bounds for the era.",
        "Check the value of the text in the element.",
    ),
    ErrorCode.UNSUPPORTED_LITERAL_FACT_FORMAT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "608",
        "Unsupported literal fact format '{format}'.",
        "Check the name of the format attribute of the element.",
    ),
    ErrorCode.UNSUPPORTED_NON_NUMERIC_FACT_FORMAT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "609",
        "Unsupported non-numeric fact format '{format}'.",
        "Check the name of the format attribute of the element.",
    ),
    ErrorCode.UNSUPPORTED_NON_FRACTION_FACT_FORMAT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "620",
        "Unsupported non-fraction fact format '{format}'.",
        "Check the value of the format attribute of the element.",
    ),
    ErrorCode.NUMBER_DOES_NOT_MATCH_EXPECTED_FORMAT: lambda: ErrorInstance(
        Severity.ERROR,
        Area.IXBRL_INSTANCE,
        "621",
        "Number '{number}' does not match the expected format '{format}'.",
        "Check the value of the number.",
    ),
    ErrorCode.INVALID_SCALE_ATTRIBUTE_VALUE: lambda: ErrorInstance(
        Severity.WARNING,
        Area.IXBRL_INSTANCE,
        "622",
        "Invalid scale attribute value '{scale}'. Assuming scale=0.",
        "Check the value of the scale attribute.",
    ),
    # General Linkbase
    ErrorCode.ROLEREF_INVALID_LINKTYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "100",
        "The link:(arc)roleRef element has an invalid xlink:linktype attribute '{linktype}'. This must always be set to 'simple'",
        "Set the xlink:linktype attribute to 'simple'.",
    ),
    ErrorCode.ROLEREF_MISSING_HREF_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "101",
        "The link:(arc)roleRef element has a missing xlink:href attribute.",
        "Add an xlink:href attribute.",
    ),
    ErrorCode.ROLEREF_INVALID_HREF_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "102",
        "The link:(arc)roleRef element has an invalid xlink:href attribute '{href}'. It should always be a valid URI.",
        "Check the value of the xlink:href attribute.",
    ),
    ErrorCode.ROLEREF_MISSING_ROLE_URI_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "103",
        "The link:(arc)roleRef element has a missing roleURI attribute.",
        "Add a roleURI attribute.",
    ),
    ErrorCode.ROLEREF_INVALID_ROLE_URI_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "104",
        "The link:(arc)roleRef element has an invalid roleURI attribute '{role_uri}'. It should always be a valid URI.",
        "Check the value of the roleURI attribute.",
    ),
    ErrorCode.ROLEREF_EMPTY_ROLE_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "105",
        "If the xlink:role attribute is present in a link:(arc)roleRef element, it must not be empty.",
        "Either remove or fill in the xlink:role attribute.",
    ),
    ErrorCode.XML_UNSUPPORTED_RESOURCE_TAG: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "200",
        "The tag '{tag}' is not a supported resource type.",
        "Check the tag of the element.",
    ),
    ErrorCode.XML_REFERENCED_LOCATOR_ELEMENT_NOT_FOUND: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "300",
        "The referenced locator element with ID '{elem_id}' could not be found.",
        "Check the value of the xlink:href attribute.",
    ),
    ErrorCode.XML_UNSUPPORTED_REFERENCED_ELEMENT_TYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "301",
        "The referenced element type must be a 'resource' or a 'locator'. {type} not a supported type.",
        "Check the value of the xlink:type attribute",
    ),
    ErrorCode.UNSUPPORTED_LINK_TYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "400",
        "The link type {type} is not supported. Supported linkbase types are 'presentation/calculation/definition/label/reference/footnoteLink'.",
        "Check the value of the link attribute",
    ),
    ErrorCode.DUPLICATE_LINKBASE_ARC: lambda: ErrorInstance(
        Severity.WARNING,
        Area.GENERAL_LINKBASE,
        "401",
        "The arc going from '{arc_from}' to '{arc_to} is defined multiple times.",
        "Remove the duplicate arcs",
    ),
    ErrorCode.MISSING_LINK_ROLE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.GENERAL_LINKBASE,
        "402",
        "A standard link element is required to have an xlink:role attribute.",
        "Set the xlink:role attribute.",
    ),
    # Label network
    ErrorCode.MISSING_LABEL_LANGUAGE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.LABEL_NETWORK,
        "001",
        "The label element has no xml:lang attribute in scope.",
        "Add an xml:lang attribute in scope of the element.",
    ),
    # Footnote network
    ErrorCode.XML_MISSING_FOOTNOTE_LANGUAGE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.FOOTNOTE_NETWORK,
        "001",
        "The footnote element has no xml:lang attribute in scope.",
        "Add an xml:lang attribute in scope of the element.",
    ),
    # Taxonomy package
    ErrorCode.INVALID_CATALOG_ROOT_NODE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.TAXONOMY_PACKAGE,
        "000",
        "The root node of the catalog should be a <{{urn:oasis:names:tc:entity:xmlns:xml:catalog}}catalog> element.",
        "Check the root node of the catalog and its namespace.",
        QName(error_namespaces["tpe"], "tpe", "invalidCatalogFile"),
    ),
    ErrorCode.REWRITE_URI_MISSING_ATTRIBUTE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.TAXONOMY_PACKAGE,
        "001",
        "The rewriteURI element is missing either a 'uriStaratString' or a 'rewritePrefix' attribute.",
        "Check the attributes of the rewriteURI element.",
        QName(error_namespaces["tpe"], "tpe", "invalidCatalogFile"),
    ),
    ErrorCode.MULTIPLE_REWRITE_URIS_FOR_START_STRING: lambda: ErrorInstance(
        Severity.ERROR,
        Area.TAXONOMY_PACKAGE,
        "002",
        "The catalog contains multiple rewriteURI elements with equivalent 'uriStartString' URIs: lambda: ErrorInstance(uri}",
        "Check the rewriteURI elements for typos or duplication.",
        QName(error_namespaces["tpe"], "tpe", "multipleRewriteURIsForStartString"),
    ),
    # Validation
    ErrorCode.MULTIPLE_PRESENTATION_NETWORKS_IN_COMPONENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.VALIDATION,
        "000",
        "Component {linkrole_uri} has more than one presentation network.",
        "Check the linkroles of the networks in the component",
    ),
    ErrorCode.MULTIPLE_CALCULATION_NETWORKS_IN_COMPONENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.VALIDATION,
        "001",
        "Component {linkrole_uri} has more than one calculation network.",
        "Check the linkroles of the networks in the component",
    ),
    ErrorCode.MULTIPLE_DEFINITION_NETWORKS_IN_COMPONENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.VALIDATION,
        "002",
        "Component {linkrole_uri} has more than one definition network.",
        "Check the linkroles of the networks in the component",
    ),
    # Schema
    ErrorCode.PRESENTATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.SCHEMA_DEFINITION,
        "000",
        "Component {linkrole_uri} has a presentation network but without an appropriate usedOn element in its schema.",
        "Add a `<link:usedOn>link:presentationLink</link:usedOn>` element in the component.",
    ),
    ErrorCode.CALCULATION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.SCHEMA_DEFINITION,
        "001",
        "Component {linkrole_uri} has a calculation network but without an appropriate usedOn element in its schema.",
        "Add a `<link:usedOn>link:calculationLink</link:usedOn>` element in the component.",
    ),
    ErrorCode.DEFINITION_NETWORK_IN_COMPONENT_WITHOUT_USEDON_ELEMENT: lambda: ErrorInstance(
        Severity.WARNING,
        Area.SCHEMA_DEFINITION,
        "002",
        "Component {linkrole_uri} has a definition network but without an appropriate usedOn element in its schema.",
        "Add a `<link:usedOn>link:definitionLink</link:usedOn>` element in the component.",
    ),
    ErrorCode.REFERENCED_SCHEMA_ELEMENT_NOT_FOUND: lambda: ErrorInstance(
        Severity.ERROR,
        Area.SCHEMA_DEFINITION,
        "100",
        "The referenced schema element with ID '{ref_id}' could not be found in the schema with name {ref_schema_name}.",
        "Check the value of the xlink:href attribute.",
    ),
    ErrorCode.INVALID_CONCEPT_PERIOD_TYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.SCHEMA_DEFINITION,
        "200",
        "The concept period type '{period_type}' for concept {concept_name} is not valid. Valid values are 'instant' and 'duration'.",
        "Check the value of the xbrli:periodType attribute.",
    ),
    ErrorCode.INVALID_CONCEPT_BALANCE_TYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.SCHEMA_DEFINITION,
        "201",
        "The concept balance type '{balance_type}' for concept {concept_name} is not valid. Valid values are 'credit' and 'debit'.",
        "Check the value of the xbrli:balance attribute.",
    ),
    ErrorCode.INVALID_CONCEPT_NILLABLE_VALUE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.SCHEMA_DEFINITION,
        "202",
        "The concept nillable value '{nillable_value}' for concept {concept_name} is not valid. Valid values are 'true' and 'false'.",
        "Check the value of the nillable attribute.",
    ),
    ErrorCode.MISSING_CONCEPT_DATA_TYPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.SCHEMA_DEFINITION,
        "203",
        "Concept {concept_name} is missing a data type.",
        "Add a 'type' attribute to the definition of the concept.",
    ),
    # Misc
    ErrorCode.QNAME_NAMESPACE_NOT_IN_ELEMENT_SCOPE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.MISC,
        "000",
        "QName namespace '{namespace}' is not in element scope",
        "Check for a misspelling in the QName's prefix",
    ),
    ErrorCode.QNAME_MISSING_NAMESPACE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.MISC,
        "001",
        "QName '{local_name}' is missing a namespace (and a default one is not provided)",
        "Did you forget the prefix of the local name?",
    ),
    ErrorCode.UNAVAILABLE_REMOTE_FILE: lambda: ErrorInstance(
        Severity.ERROR,
        Area.MISC,
        "100",
        "The remote file with '{uri}' could not be found. The web page returned status code {status_code}.",
        "Check the URI of the remote file.",
    ),
}
