from .brel_aspect import Aspect

from .i_characteristic import ICharacteristic

from .concept_characteristic import ConceptCharacteristic
from .entity_characteristic import EntityCharacteristic
from .explicit_dimension_characteristic import ExplicitDimensionCharacteristic
from .period_characteristic import PeriodCharacteristic
from .typed_dimension_characteristic import TypedDimensionCharacteristic
from .unit_characteristic import UnitCharacteristic
