name: TestPyPI

on: workflow_dispatch

jobs:
  linter:
    name: Lint and typecheck
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install project
      run: make install
    - name: Check source fomatting
      run: make black-src
    - name: Typecheck source
      run: make mypy-src
    - name: Check tests formatting 
      run: make black-test
    - name: Typecheck tests
      run: make mypy-test

  tests:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install project
      run: make install
    - name: Run tests
      run: make test-ci
          
  build-for-deploy:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install setup tools
      run: pip install setuptools
    - name: Build the wheel and distribution package
      run: python setup.py sdist bdist_wheel
    - name: Store the distribution packages
      uses: actions/upload-artifact@v6
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - linter
    - tests
    - build-for-deploy
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/jsoniq
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download the artifact with the distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
